// Exporting metadata object
export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
  };
  
  // Exporting default function
  export default function RootLayout({ children }) {
    return (
      // Returning JSX
      <html lang="en">
        <body>{children}</body>
      </html>
    );
  }
  